void rf12_initialize(uint8_t id, uint8_t g);
void rf12_send(uint8_t len);
void rf12_rx_on(void);
void rf12_rx_off(void);
extern char* rf12_data;
extern uint8_t receiving;
extern uint8_t rcv_done;
extern uint8_t rf12_debug;
extern uint8_t rf12_len;
void print_buf(void);
uint16_t rf12_read_status();
